# Generated by Django 4.2.2 on 2023-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
