# Generated by Django 4.2.2 on 2023-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pics_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pics',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
